[package]
name = "rust-lab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
macroquad = "0.3.24"
num = "0.4.0"
rand = "0.8.5"

[profile.release]
lto = "fat"
strip = true
